 
-- Q1) SECTION 1 : Langages de définition de données (DDL)
-- Q1) PARTIE 1 : Création des tables
-- Jouer : table des joueurs
CREATE TABLE Jouer (
    ID_Jouer NUMBER NOT NULL,
    Pseudo VARCHAR2(32) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    Age NUMBER(3) NOT NULL,
    Pays VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_jouer PRIMARY KEY (ID_Jouer)

);

-- Jeu : table des jeux avec clé primaire identity
CREATE TABLE Jeu (
    ID_Jeu NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Titre VARCHAR2(255) NOT NULL,
    Genre VARCHAR2(100) NOT NULL,
    ClassificationAge VARCHAR2(10) NOT NULL,
    Plateform VARCHAR2(20) NOT NULL,
    ID_StudioDev NUMBER NOT NULL,
    CONSTRAINT pk_jeu PRIMARY KEY (ID_Jeu)
);

-- Achat : achats (clé primaire composée)
CREATE TABLE Achat (
    ID_Jouer NUMBER NOT NULL,
    ID_Jeu NUMBER NOT NULL,
    DateAchat DATE ,
    CONSTRAINT pk_achat PRIMARY KEY (ID_Jouer, ID_Jeu)
);

-- SessionJeu : session de jeu avec durée en INTERVAL
CREATE TABLE SessionJeu (
    ID_Session NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DateSession DATE NOT NULL,
    DureeSession INTERVAL DAY(0) TO SECOND(0) ,
    ID_Jouer NUMBER NOT NULL,
    CONSTRAINT pk_session PRIMARY KEY (ID_Session)
);

-- TROPHEE : trophées (nom renommé pour éviter l'accent)
CREATE TABLE TROPHEE (
    ID_TROPHEE NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NomTrophee VARCHAR2(255) NOT NULL,
    Points NUMBER NOT NULL,
    ID_Jeu NUMBER NOT NULL,
    CONSTRAINT pk_trophee PRIMARY KEY (ID_TROPHEE)
);

-- StudioDev : studio de développement
CREATE TABLE StudioDev (
    ID_StudioDev NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NomStudio VARCHAR2(255) NOT NULL,
    DateCreation DATE NOT NULL,
    CONSTRAINT pk_studiodev PRIMARY KEY (ID_StudioDev)
);

-- Clés étrangères
ALTER TABLE TROPHEE ADD CONSTRAINT trophee_id_jeu_fk FOREIGN KEY (ID_Jeu) REFERENCES Jeu (ID_Jeu);
ALTER TABLE SessionJeu ADD CONSTRAINT sessionjeu_id_jouer_fk FOREIGN KEY (ID_Jouer) REFERENCES Jouer (ID_Jouer);
ALTER TABLE Achat ADD CONSTRAINT achat_id_jouer_fk FOREIGN KEY (ID_Jouer) REFERENCES Jouer (ID_Jouer);
ALTER TABLE Jeu ADD CONSTRAINT jeu_id_studiodev_fk FOREIGN KEY (ID_StudioDev) REFERENCES StudioDev (ID_StudioDev);
ALTER TABLE Achat ADD CONSTRAINT achat_id_jeu_fk FOREIGN KEY (ID_Jeu) REFERENCES Jeu (ID_Jeu);

-- Contraintes CHECK pour la classification et la plateforme
ALTER TABLE Jeu ADD CONSTRAINT jeu_classificationage_check CHECK (ClassificationAge IN ('E','E10+','T','M','AO'));
ALTER TABLE Jeu ADD CONSTRAINT jeu_plateform_check CHECK (Plateform IN ('XBOX','PLAYSTATION','SWITCH','PC','MOBILE'));
